use_frameworks!
inhibit_all_warnings!

platform :ios, '12.0'

target 'PhotoCropper_Example' do
  pod 'PhotoCropper', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end